typography_spectrum: 0.6291373744606972
content_rating:
  adult: false
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#70AD47'
    - '#00FF00'
    - '#CFCFCF'
  brandStrength: 0.3773911993484944
  lightness: 0.3411832069978118
  saturation: 0.4217274314723909
  rhythmicContrast: 0.7489525778219104
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.2579420767724514
author: {}
name: showmehowtovote
url: 'http://showmehowtovote.co.uk/'
navigation:
  - name: How To Vote
    id: f0dd0367-be32-4e21-a53e-24b2f790c8d6
    type: content
  - name: Postal Voting Explained
    id: 1b231136-fb7a-49b7-864f-0404c3059bd7
    type: content
  - name: National Insurance Number Help
    id: f729673c-2c68-4d1c-a527-a3f17b0d964c
    type: content
  - name: Manifesto Info
    id: 5babdd8a-15d8-479c-bbba-895902b1bf57
    type: content
title: Show me how to vote
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FQhLk8AKh19c%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DQhLk8AKh19c&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FQhLk8AKh19c%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      isBasedOnUrl: 'https://youtu.be/QhLk8AKh19c'
      keywords:
        - kinolibrary
        - kino library
        - stock footage
        - archive
        - footage
        - 1997 general election
        - '1997'
        - 1990s
        - general election
        - new labour
        - polling station
        - voting
        - electi...
      author:
        - name: thekinolibrary
          url: 'https://www.youtube.com/user/thekinolibrary'
          avatar: {}
      '@context': 'http://schema.org'
      title: '1997 UK General Election, People Voting, Polling Stations'
      '@type': VideoObject
      publisher:
        name: YouTube
        domain: youtu.be
        url: 'https://www.youtube.com/'
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
      description: >-
        From the Kinolibrary archive film collections. To order the clip clean
        and high res visit http://www.kinolibrary.com. Clip ref DW022029 1997 UK
        General Election, people voting
      starred: false
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Voting made easy
purpose:
  - type: external
    url: 'https://www.gov.uk/register-to-vote'
    label: Register Now
  - type: external
    url: 'https://www.gov.uk/voting-in-the-uk/postal-voting'
    label: Vote by post
