name: showmehowtovote
layout_spectrum: 0.2579420767724514
typography_spectrum: 0.6291373744606972
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#70AD47'
    - '#00FF00'
    - '#CFCFCF'
  brandStrength: 0.3773911993484944
  lightness: 0.3411832069978118
  saturation: 0.4217274314723909
  rhythmicContrast: 0.7489525778219104
purpose:
  - type: external
    url: 'https://www.gov.uk/register-to-vote'
    label: Register right here
  - type: external
    url: 'https://www.gov.uk/voting-in-the-uk/postal-voting'
    label: Vote by post
title: Show me how to vote
description: Voting made easy
author: {}
content_rating:
  adult: false
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FQhLk8AKh19c%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DQhLk8AKh19c&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FQhLk8AKh19c%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      '@type': VideoObject
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/QhLk8AKh19c'
      keywords:
        - kinolibrary
        - kino library
        - stock footage
        - archive
        - footage
        - 1997 general election
        - '1997'
        - 1990s
        - general election
        - new labour
        - polling station
        - voting
        - electi...
      title: '1997 UK General Election, People Voting, Polling Stations'
      publisher:
        name: YouTube
        domain: youtu.be
        url: 'https://www.youtube.com/'
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
      author:
        - name: thekinolibrary
          url: 'https://www.youtube.com/user/thekinolibrary'
          avatar: {}
      starred: false
      description: >-
        From the Kinolibrary archive film collections. To order the clip clean
        and high res visit http://www.kinolibrary.com. Clip ref DW022029 1997 UK
        General Election, people voting
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
